on:
  create # does not support filtering by type (branch), must do later

jobs:
  create-branch:
    if: github.ref_type == 'branch' # create can be branches or tags; we want only branches
    runs-on: ubuntu-latest

    steps:

    - name: Check out everything from main
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: source

    - name: Dump GitHub context
      run: |
        cp -r source __branch_${{ github.ref_name }}
        cd __branch_${{ github.ref_name }}
        git init -b main
        git add .
        git commit -m "Branched off ${{ github.event.repository.name }}"
        git push
