defaults:
  run:
    shell: bash -v {0}

on:
  create # does not support filtering by type (branch), must do later

jobs:
  create-branch:
    if: github.ref_type == 'branch' # create can be branches or tags; we want only branches
    runs-on: ubuntu-latest

    steps:

    - name: Create New Repo for Branch
      id: new-repo
      run: |
        sanitized_branch=$(echo '${{ github.ref_name }}' | sed -e "s/[^a-zA-Z0-9._-]/-/g")
        new_repo_name="__branch_$sanitized_branch"
        echo "repo_name=$new_repo_name" >> $GITHUB_OUTPUT
        gh repo create $new_repo_name --public
        gh workflow --repo ${{ github.repository_owner }}/$new_repo_name enable "on-branch.yml"
        gh secret --repo ${{ github.repository_owner }}/$new_repo_name set CROSS_REPO_GITHUB_TOKEN --body "${{ secrets.CROSS_REPO_GITHUB_TOKEN }}"
        gh variable --repo ${{ github.repository_owner }}/$new_repo_name set SOURCE_REPO --body "${{ github.event.repository.name }}"
        gh variable --repo ${{ github.repository_owner }}/$new_repo_name set SOURCE_BRANCH --body "${{ github.ref_name }}"
      env:
        GH_TOKEN: ${{ secrets.CROSS_REPO_GITHUB_TOKEN }}

    - name: Copy HEAD of Site Into New Repo
      run: |
        git clone --bare --single-branch https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}
        cd ${{ github.event.repository.name }}.git
        git push --mirror https://${{ secrets.CROSS_REPO_GITHUB_TOKEN }}@github.com/${{ github.repository_owner }}/${{ steps.new-repo.outputs.repo_name }}

    - name: Clean Up on Failure
      if: ${{ failure() }}
      run: |
        cd ${{ github.event.repository.name }}.git
        gh repo delete ${{ steps.new-repo.outputs.repo_name }} --yes
        git push https://${{ secrets.CROSS_REPO_GITHUB_TOKEN }}@github.com/${{ github.repository_owner }}/${{ github.event.repository.name }} -d ${{ github.ref_name }}
      env:
        GH_TOKEN: ${{ secrets.CROSS_REPO_GITHUB_TOKEN }}
