on:
  create # does not support filtering by type (branch), must do later

jobs:
  create-branch:
    if: github.ref_type == 'branch' # create can be branches or tags; we want only branches
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
