defaults:
  run:
    shell: bash -v {0}

env:
  GH_TOKEN: ${{ secrets.CROSS_REPO_GITHUB_TOKEN }}

on:
  delete # does not support filtering by type (branch), must do later

jobs:
  delete-branch:
    if: github.ref_type == 'branch' # create can be branches or tags; we want only branches
    runs-on: ubuntu-latest

    steps:

    - name: Calculate Name of Target Repo
      id: repo
      run: |
        sanitized_branch=$(echo '${{ github.event.ref }}' | sed -e "s/[^a-zA-Z0-9._-]/-/g")
        target_repo_name="__branch_$sanitized_branch"
        echo "name=$target_repo_name" >> $GITHUB_OUTPUT

    - name: Delete Target Repo Corresponding to Branch
      run: |
        gh repo delete ${{ steps.repo.outputs.name }} --yes
