name: On Commit

defaults:
  run:
    shell: bash -v {0}

env:
  GH_TOKEN: ${{ secrets.CROSS_REPO_GITHUB_TOKEN }}

on:
  push:
    branches-ignore:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Dump Context
        run: |
          echo "${{ toJson(github) }}"
